CREATE TABLE USERS (
  ID BIGSERIAL PRIMARY KEY,
  USERNAME VARCHAR NOT NULL UNIQUE,
  PASSWORD VARCHAR NOT NULL,
  ROLE VARCHAR NOT NULL
);

CREATE TABLE JWT (
  ID BIGSERIAL PRIMARY KEY,
  USER_ID BIGINT NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
  JWT VARCHAR NOT NULL,
  EXPIRATION TIMESTAMP NOT NULL
);

CREATE TABLE COMPANY (
  ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR NOT NULL
);

CREATE TABLE CATEGORY (
  ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR NOT NULL
);

CREATE TABLE ITEM (
  ID BIGSERIAL PRIMARY KEY,
  COMPANY_ID BIGINT NOT NULL REFERENCES COMPANY (ID) ON DELETE CASCADE,
  CATEGORY_ID BIGINT NOT NULL REFERENCES CATEGORY (ID) ON DELETE CASCADE,
  NAME VARCHAR NOT NULL,
  PRICE DECIMAL(12, 2)
);