CREATE TABLE USERS (
  ID BIGSERIAL PRIMARY KEY,
  USERNAME VARCHAR NOT NULL UNIQUE,
  PASSWORD VARCHAR NOT NULL,
  ROLE VARCHAR NOT NULL
);

CREATE TABLE JWT (
  ID BIGSERIAL PRIMARY KEY,
  JWT VARCHAR NOT NULL,
  USER_ID BIGINT NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
  EXPIRATION TIMESTAMP NOT NULL
);