INSERT INTO category (name) VALUES ('Pastry');
INSERT INTO category (name) VALUES ('Meat');
INSERT INTO category (name) VALUES ('Drinks');
INSERT INTO category (name) VALUES ('Fruit');
INSERT INTO category (name) VALUES ('Cheese');
INSERT INTO category (name) VALUES ('Chocolate');
INSERT INTO category (name) VALUES ('Bread');
INSERT INTO category (name) VALUES ('Coffee');
INSERT INTO category (name) VALUES ('Soup');
INSERT INTO category (name) VALUES ('Vegetable');
INSERT INTO category (name) VALUES ('Oil');
INSERT INTO category (name) VALUES ('Pasta');
INSERT INTO category (name) VALUES ('Fish');
INSERT INTO category (name) VALUES ('Cookies');
INSERT INTO category (name) VALUES ('Spices');
INSERT INTO category (name) VALUES ('Sauce');
INSERT INTO category (name) VALUES ('Ice Cream');

INSERT INTO company (name) VALUES ('Pouros and Sons');
INSERT INTO company (name) VALUES ('Nikolaus-Abbott');
INSERT INTO company (name) VALUES ('Torphy, Jerde and Paucek');
INSERT INTO company (name) VALUES ('Stoltenberg Group');
INSERT INTO company (name) VALUES ('Wuckert-Jones');
INSERT INTO company (name) VALUES ('Wehner and Schamberger');
INSERT INTO company (name) VALUES ('Abshire and Kulas');
INSERT INTO company (name) VALUES ('Lang-Koepp');
INSERT INTO company (name) VALUES ('Terry-Waters');
INSERT INTO company (name) VALUES ('Fisher-Lubowitz');
INSERT INTO company (name) VALUES ('Hettinger Inc');
INSERT INTO company (name) VALUES ('Nader LLC');
INSERT INTO company (name) VALUES ('Dietrich-Gislason');

INSERT INTO item(company_id,category_id,name,price) VALUES (9,7,'Bread - Raisin Walnut Oval',24.44);
INSERT INTO item(company_id,category_id,name,price) VALUES (5,2,'Longos - Chicken Cordon Bleu',28.33);
INSERT INTO item(company_id,category_id,name,price) VALUES (2,7,'Bread - Crumbs, Bulk',11.63);
INSERT INTO item(company_id,category_id,name,price) VALUES (7,4,'Apples - Spartan',15.35);
INSERT INTO item(company_id,category_id,name,price) VALUES (2,3,'Smirnoff Green Apple Twist',28.57);
INSERT INTO item(company_id,category_id,name,price) VALUES (7,3,'Wine - Vovray Sec Domaine Huet',28.7);
INSERT INTO item(company_id,category_id,name,price) VALUES (4,16,'Sauce - Alfredo',9.9);
INSERT INTO item(company_id,category_id,name,price) VALUES (1,16,'Wasabi Paste',38.43);
INSERT INTO item(company_id,category_id,name,price) VALUES (8,10,'Ginger - Pickled',23.58);
INSERT INTO item(company_id,category_id,name,price) VALUES (12,10,'Pepper - Julienne, Frozen',5.95);
INSERT INTO item(company_id,category_id,name,price) VALUES (5,2,'Beef - Ground, Extra Lean, Fresh',36.85);
INSERT INTO item(company_id,category_id,name,price) VALUES (9,2,'Okra',14.17);
INSERT INTO item(company_id,category_id,name,price) VALUES (11,10,'Pumpkin - Seed',21.2);
INSERT INTO item(company_id,category_id,name,price) VALUES (1,7,'Bread Fig And Almond',11.76);
INSERT INTO item(company_id,category_id,name,price) VALUES (11,11,'Oil - Pumpkinseed',35.63);
INSERT INTO item(company_id,category_id,name,price) VALUES (9,3,'Carbonated Water - Peach',24.84);
INSERT INTO item(company_id,category_id,name,price) VALUES (12,3,'Wine - Riesling Alsace Ac 2001',33.89);
INSERT INTO item(company_id,category_id,name,price) VALUES (10,2,'Pork - Back Ribs',26.75);
INSERT INTO item(company_id,category_id,name,price) VALUES (8,2,'Beef - Eye Of Round',31.69);
INSERT INTO item(company_id,category_id,name,price) VALUES (10,3,'Pate - Cognac',34.63);
INSERT INTO item(company_id,category_id,name,price) VALUES (9,17,'Ice Cream Bar - Rolo Cone',1.32);
INSERT INTO item(company_id,category_id,name,price) VALUES (3,3,'Wine - Fino Tio Pepe Gonzalez',26.97);
INSERT INTO item(company_id,category_id,name,price) VALUES (2,3,'Juice - Orange, Concentrate',29.62);
INSERT INTO item(company_id,category_id,name,price) VALUES (5,3,'Yoplait - Strawbrasp Peac',29.48);
INSERT INTO item(company_id,category_id,name,price) VALUES (8,3,'Appetizer - Escargot Puff',21.62);
INSERT INTO item(company_id,category_id,name,price) VALUES (13,10,'Basil - Fresh',12.88);
INSERT INTO item(company_id,category_id,name,price) VALUES (4,17,'Icecream - Dstk Cml And Fdg',37.48);
INSERT INTO item(company_id,category_id,name,price) VALUES (2,3,'Wine - Taylors Reserve',12.7);
INSERT INTO item(company_id,category_id,name,price) VALUES (10,4,'Banana - Leaves',34.23);
INSERT INTO item(company_id,category_id,name,price) VALUES (1,3,'Wine - German Riesling',31.16);
INSERT INTO item(company_id,category_id,name,price) VALUES (6,3,'Wine - Ice Wine',30.12);
INSERT INTO item(company_id,category_id,name,price) VALUES (13,3,'Wine - Sherry Dry Sack, William',24.17);
INSERT INTO item(company_id,category_id,name,price) VALUES (9,10,'Quinoa',8.02);
INSERT INTO item(company_id,category_id,name,price) VALUES (8,2,'Pork - Tenderloin, Frozen',37.09);
INSERT INTO item(company_id,category_id,name,price) VALUES (7,7,'Bread - White Mini Epi',32.75);
INSERT INTO item(company_id,category_id,name,price) VALUES (3,6,'Chocolate - Mi - Amere Semi',22.03);
INSERT INTO item(company_id,category_id,name,price) VALUES (1,3,'Beer - Camerons Cream Ale',22.37);
INSERT INTO item(company_id,category_id,name,price) VALUES (5,13,'Fish - Soup Base, Bouillon',38.59);
INSERT INTO item(company_id,category_id,name,price) VALUES (5,11,'Oil - Cooking Spray',36.48);
INSERT INTO item(company_id,category_id,name,price) VALUES (9,3,'Mix Pina Colada',23.72);
INSERT INTO item(company_id,category_id,name,price) VALUES (7,7,'Bread - Assorted Rolls',14.0);
INSERT INTO item(company_id,category_id,name,price) VALUES (3,10,'Split Peas - Green, Dry',30.05);
INSERT INTO item(company_id,category_id,name,price) VALUES (9,3,'Calypso - Black Cherry Lemonade',6.68);
INSERT INTO item(company_id,category_id,name,price) VALUES (9,13,'Squid - Breaded',25.16);