CREATE TABLE PAYMENT (
  ID BIGSERIAL PRIMARY KEY,
  PAYER VARCHAR NOT NULL,
  CREDIT_CARD VARCHAR NOT NULL
);

CREATE TABLE USER_ORDER (
  ID BIGSERIAL PRIMARY KEY,
  PAYMENT_ID BIGINT NOT NULL REFERENCES PAYMENT (ID) ON DELETE CASCADE,
  STATUS VARCHAR NOT NULL,
  PRICE DECIMAL(12, 2)
);

CREATE TABLE USER_ORDER_ITEM (
  ID BIGSERIAL PRIMARY KEY,
  ORDER_ID BIGINT NOT NULL REFERENCES USER_ORDER (ID),
  ITEM_ID BIGINT NOT NULL REFERENCES ITEM (ID),
  QUANTITY INTEGER NOT NULL,
  PRICE DECIMAL(12, 2)
);